[project]
name = "orbebot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py==2.4.0",
    "mcrcon==0.7.0",
    "requests==2.32.3",
]
